## Ubuntu server 22.04 LTS (HVM), SSD Volume Type
## Ami: ami-03f4fa076d2981b45
## aws ssm get-parameters --profile telasa --names /aws/service/canonical/ubuntu/server/22.04/stable/current/amd64/hvm/ebs-gp2/ami-id --query 'Parameters[0].[Value]' --output text

AWSTemplateFormatVersion: 2010-09-09

Parameters:
  AmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/canonical/ubuntu/server/22.04/stable/current/amd64/hvm/ebs-gp2/ami-id'

  AppName:
    Type: String
    Default: 'VideoPass'

  ImageVersion:
    Type: String
    Default: '1.0.0'

Resources:

  InstanceRole:
    Type: AWS::IAM::Role
    Metadata:
      Comment: Role to be used by instance during image build.
    Properties:
      ManagedPolicyArns:
        - Fn::Sub: arn:${AWS::Partition}:iam::aws:policy/AmazonSSMManagedInstanceCore
        - Fn::Sub: arn:${AWS::Partition}:iam::aws:policy/EC2InstanceProfileForImageBuilder
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - !Sub 'ec2.${AWS::URLSuffix}'
        Version: '2012-10-17'
      Path: /executionServiceEC2Role/

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /executionServiceEC2Role/
      Roles:
        - Ref: InstanceRole

  Ubuntu2204ImageInfrastructureConfiguration:
    Type: AWS::ImageBuilder::InfrastructureConfiguration
    Properties:
      Name: Ubuntu-2204-with-latest-SSM-Agent-Infrastructure-Configuration
      InstanceProfileName:
        Ref: InstanceProfile

  Ubuntu2204LogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      LogGroupName: /aws/imagebuilder/Ubuntu-2204-with-latest-SSM-Agent
      RetentionInDays: 3

  Ubuntu2204ImageRecipe:
    Type: AWS::ImageBuilder::ImageRecipe
    Properties:
      Name: Ubuntu-2204-with-latest-SSM-Agent
      Version: !Ref ImageVersion
      ParentImage: !Ref AmiId
      Components:
        - ComponentArn: !GetAtt KKStreamComponent.Arn
      AdditionalInstanceConfiguration:
        UserDataOverride:
          Fn::Base64:
            Fn::Sub: |
              #!/bin/bash
              sudo systemctl stop snap.amazon-ssm-agent.amazon-ssm-agent.service
              sudo snap refresh amazon-ssm-agent --channel=candidate
              sudo systemctl start snap.amazon-ssm-agent.amazon-ssm-agent.service

  KKStreamComponent:
    Type: AWS::ImageBuilder::Component
    Properties:
      Name: !Sub "${AppName} Component" 
      Platform: Linux
      Version: !Ref ImageVersion
      Data: |
        name: InstallVideopassDependencies
        description: Install the latest version of Videopass app dependencies
        schemaVersion: 1.0
        phases:
          - name: build
            steps:
              - name: InstallAWSDependencies
                action: ExecuteBash
                inputs:
                  commands:
                    - sudo apt update -y && sudo apt install python3 wget htop dnsutils nload ncdu curl jq zip unzip git build-essential && sudo apt autoremove -y --purge
                    - cd ~/ && curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && sudo unzip awscliv2.zip && ./aws/install && rm -r ./aws
                    - cd ~/ && wget https://s3.amazonaws.com/amazoncloudwatch-agent/ubuntu/amd64/latest/amazon-cloudwatch-agent.deb && sudo dpkg -i ./amazon-cloudwatch-agent.deb && rm ./amazon-cloudwatch-agent.deb

  Ubuntu2204WithLatestSSMAgent:
    Type: AWS::ImageBuilder::Image
    Properties:
      ImageRecipeArn:
        Ref: Ubuntu2204ImageRecipe
      InfrastructureConfigurationArn:
        Ref: Ubuntu2204ImageInfrastructureConfiguration

  Ubuntu2204WithLatestSSMAgentParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /videopass/images/Ubuntu2204-LatestSSMAgent
      Type: String
      Value:
        Fn::GetAtt: [Ubuntu2204WithLatestSSMAgent, ImageId]
